import Head from "next/head";
import { Box, Flex, Button, useDisclosure, Divider } from "@chakra-ui/react";
import { api } from "~/utils/api";
import PostCard from "~/components/posts/postCard";
import CreatePost from "~/components/posts/createPost";
import EditPost from "~/components/posts/editPost";
import { useState } from "react";

export default function Home() {
  const { data: posts, refetch } = api.posts.getPosts.useQuery();
  const [selectedPostId, setSelectedPostId] = useState<number | null>(null);
  const {
    isOpen: createIsOpen,
    onOpen: createOnOpen,
    onClose: createOnClose,
  } = useDisclosure();

  const {
    isOpen: editIsOpen,
    onOpen: editOnOpen,
    onClose: editOnClose,
  } = useDisclosure();

  return (
    <>
      <Head>
        <title>MyLocal Test Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row items-center justify-center bg-[#ecf0f1]">
        <Flex alignSelf={"flex-start"} width={"300px"} direction={"column"}>
          <CreatePost
            isOpen={createIsOpen}
            onClose={createOnOpen}
            onOpen={createOnClose}
            refetchPosts={refetch}
          />
          <EditPost
            isOpen={editIsOpen}
            onClose={editOnClose}
            onOpen={editOnOpen}
            refetchPosts={refetch}
            post_id={selectedPostId}
          />

          <Box
            alignSelf={"center"}
            borderRadius={"4px"}
            padding={4}
            display={"flex"}
            flexDirection={"column"}
          >
            <Button
              bg={"#3498db"}
              _hover={{ bg: "#2980b9" }}
              color={"white"}
              borderRadius={"4px"}
              onClick={createOnOpen}
            >
              Add New Post
            </Button>
          </Box>

          <Divider
            width={"100%"}
            my={4}
            borderWidth={"1px"}
            borderColor={"#2980b9"}
          />
          {posts?.map((post) => (
            <PostCard
              post={post}
              refetchPosts={refetch}
              onEdit={editOnOpen}
              setSelectedPostId={setSelectedPostId}
            />
          ))}
        </Flex>
      </main>
    </>
  );
}
