import Head from "next/head";
import Link from "next/link";
import { Box, Textarea } from "@chakra-ui/react";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.posts.hello.useQuery({ text: "from tRPC" });

  const posts = api.posts.getPosts.useQuery();
  return (
    <>
      <Head>
        <title>MyLocal Test Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#ecf0f1]">
        <Box justifySelf={"flex-start"}>
          <Textarea bg={"#d1d1d1"} />
        </Box>
      </main>
    </>
  );
}
